apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: japahubs/messenger
      context: ./messenger
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: japahubs/app
      context: ./app
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    # - ./infra/helm/nats/k8s/pv-volume.yaml
    # - ./infra/helm/nats/k8s/pv-claim.yaml
deploy:
  kubectl: {}
  helm:
    releases:
      - name: nats-srv
        valuesFiles:
          - ./infra/helm/nats/values.yaml
        remoteChart: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
